### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by icklerly** [LCAD-UFES/publications-tabelini-ijcnn-2019#1]
Hi, 

your paper looks great!
Could you please provide the config file you used for the training?

Thanks in advance!
Best regards,
Lydia

**Comment by lucastabelini** [comment]
Thank you for your interest. The training settings I used were as follows:
```yaml
TRAIN:
  BG_THRESH_LO: 0.0
  SNAPSHOT_ITERS: 10000
  MAX_ITERS: 70000
  SNAPSHOT_KEPT: 100
  STEPSIZE: [20000]
  USE_HORIZONTAL_FLIPPED: False
  USE_VERTICAL_FLIPPED: False
  SCALES: [1500]
  MAX_SIZE: 1500
  BATCH_SIZE: 64
TEST:
  SCALES: [3500]
  MAX_SIZE: 2060
ANCHOR_SCALES: [0.5, 1.0, 2.0, 4.0, 8.0, 16.0]
ANCHOR_RATIOS: [1]
KEEP_AREA: True
```

Please feel free to ask any more questions you may have about the paper.
